import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
	src: "./fonts/Nunito-VariableFont_wght.ttf",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${nunito.className} antialiased`}>
			<body className="flex flex-col min-h-svh flex-nowrap relative">
				<main className="flex-1 flex flex-col items-center justify-center">
					{children}
				</main>
			</body>
		</html>
	);
}
